name: Teste de Performance com JMeter
run-name: Branch->${{ github.ref_name }} Env->${{ inputs.ambiente }} Dir->${{ inputs.diretorio }}


on:
  workflow_dispatch:
    inputs:
      integracao:
        description: "Integracao a ser executada"
        required: true
        default: "CAD2002"
        type: choice
        options:
          - CAD2002
          - CAD2003
          - PAR2101
          - PAR3005
          - MOV0002
          - MOV0001      
      usuarios:
        description: 'Quantidade de usuarios (limite maximo 10)'
        required: true
        default: "10"
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"    
      tempo:
        description: 'Tempo maximo em milessegundos)'
        required: true
        default: "60000"
        type: choice
        options:
          - "60000"
          - "600000"
          - "1200000"
          - "1800000"
          - "2400000"
          - "3000000"
          - "3600000"             
env:
  USUARIOS: ${{ inputs.usuarios }}
  INTEGRACAO: ${{ inputs.integracao }}
  DIRETORIO: ${{ inputs.diretorio }}
  VERSAO: ${{ inputs.versao }}
  TEMPO: ${{ inputs.tempo }}

jobs:
  CLEANUP:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S rm -rf ${GITHUB_WORKSPACE}
          mkdir ${GITHUB_WORKSPACE}

      - name: Cleanup actions-runner
        run: |
          cd ~
          find . -type d -name 'actions_github_pages_*' -exec sh -c 'echo "Removing directory: {}" && rm -rf "{}"' \;
        continue-on-error: true

  jmeter-tests:
    needs: CLEANUP
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Baixar JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter
    
    - name: Modify Config Files in JMeter
      run: |
        echo "log_level.jmeter=DEBUG" >> jmeter/bin/jmeter.properties 

    - name: Executar teste JMeter
      run: |
        JMETER_TEST_FILE=$(jq -r '.endPoint'${{env.INTEGRACAO}} scripts/config.json)
        echo "Arquivo de teste JMeter: $JMETER_TEST_FILE"
      
        ./jmeter/bin/jmeter -JqtdUsuarios=${{env.USUARIOS}} -Jintegracao=${{env.INTEGRACAO}} -JtempoLimite=${{env.TEMPO}} -JendPointIntegracao=$JMETER_TEST_FILE -n -t test-plans/integrationsECF.jmx -l result.jtl -e -o html_report/ -j log_jmeter.log
        
        # Adicionar logs ao relatório HTML
        echo "<h2>Logs do JMeter</h2>" >> ./html_report/index.html
        echo "<pre>" >> ./html_report/index.html
        cat log_jmeter.log >> ./html_report/index.html
        echo "</pre>" >> ./html_report/index.html

    - name: Upload do resultado
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-html-report
        path: html_report/
        
    - name: Deploy HTML Report to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PAGES_TOKEN }}
        publish_dir: ./html_report/