on:
  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: test-plans/CAD2002.jmx
          outputReportsFolder: test_plans/
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: test_plans/
