name: Teste de Performance com JMeter
run-name: Branch->${{ github.ref_name }} Env->${{ inputs.ambiente }} Dir->${{ inputs.diretorio }}


on:
  workflow_dispatch:
    inputs:
      integracao:
        description: "Integracao a ser executada"
        required: true
        default: "CAD2002"
        type: choice
        options:
          - CAD2002
          - CAD2003
          - PAR2101
          - PAR3005
          - MOV0002
          - MOV0001      
      usuarios:
        description: 'Quantidade de usuarios (limite maximo 10)'
        required: true
        default: "10"
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"                
env:
  USUARIOS: ${{ inputs.usuarios }}
  INTEGRACAO: ${{ inputs.integracao }}
  DIRETORIO: ${{ inputs.diretorio }}
  VERSAO: ${{ inputs.versao }}

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest
    env : 
      MY_VARIABLE: 10 
      

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Baixar JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Executar teste JMeter
      run: |
        JMETER_TEST_FILE=$(jq -r '.endPoint'${{env.INTEGRACAO}} scripts/config.json)
        echo "Arquivo de teste JMeter: $JMETER_TEST_FILE"
      
        ./jmeter/bin/jmeter -JqtdUsuarios=${{env.USUARIOS}} -Jintegracao=${{env.INTEGRACAO}} -JendPointIntegracao=$JMETER_TEST_FILE -n -t test-plans/CAD2002.jmx -l result.jtl

    - name: Upload do resultado
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-result
        path: result.jtl