name: Teste de Carga com JMeter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Baixar JMeter
      run: |
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter

    - name: Executar teste JMeter
      run: |
        ./jmeter/bin/jmeter -n -t test-plans/CAD2002.jmx -l result.jtl

    - name: Upload do resultado
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-result
        path: result.jtl
